/*
 * Drive scripts/shots.js with JS string args so PowerShell cannot eat quotes.
 * Evidence for Configurator rounds 3 to 6: homage chrome, CLI, import,
 * presets, modes, setup, configuration features.
 */
import { spawn } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..', '..', '..');
const chrome = process.env.SIM_CHROME_BIN
  || 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';

const steps = [
  'until:!!window.__fc',
  'wait:500',
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:Enter',
  "until:window.__ui.screen==='fc'",
  'wait:400',
  'eval:window.__fc()',
  'shot:fc-pid',
  "eval:void(window.__ui.fc.setTab('cli'),window.__ui.renderMenu())",
  "until:window.__fc().tab==='cli'",
  'wait:200',
  'shot:fc-cli',
  "eval:void(window.__ui.fc.setTab('osd'),window.__ui.renderMenu())",
  "until:window.__fc().tab==='osd'",
  'wait:200',
  'shot:fc-osd',
  "eval:void(window.__ui.fc.setTab('presets'),window.__ui.renderMenu())",
  "until:window.__fc().tab==='presets'",
  'wait:200',
  'shot:fc-presets',
  "eval:void(window.__ui.fc.setTab('modes'),window.__ui.renderMenu())",
  "until:window.__fc().tab==='modes'",
  'wait:200',
  'shot:fc-modes',
  "eval:void(window.__ui.fc.setTab('setup'),window.__ui.renderMenu())",
  "until:window.__fc().tab==='setup'",
  'wait:200',
  'shot:fc-setup',
  "eval:void(window.__ui.fc.setTab('configuration'),window.__ui.renderMenu())",
  "until:window.__fc().tab==='configuration'",
  'wait:200',
  'shot:fc-configuration',
  "eval:void(window.__ui.fc.setTab('motors'),window.__ui.renderMenu())",
  "until:window.__fc().tab==='motors'",
  'wait:200',
  'shot:fc-motors',
  "eval:void(window.__ui.fc.setTab('pid'),window.__ui.fc.page='rates',window.__ui.renderMenu())",
  "until:window.__fc().page==='rates'",
  'wait:200',
  'shot:fc-rates',
  "eval:void(window.__ui.fc.setTab('receiver'),window.__ui.renderMenu())",
  "until:window.__fc().tab==='receiver'",
  'wait:200',
  'shot:fc-receiver',
  "eval:void(window.__ui.fc.setTab('pid'),window.__ui.fc.page='filters',window.__ui.renderMenu())",
  "until:window.__fc().page==='filters'",
  'wait:200',
  'shot:fc-filters',
  "eval:void(window.__ui.fc.openImport('set p_roll = 45\\nset roll_srate = 42\\n','rates.diff'),window.__ui.renderMenu())",
  "until:window.__fc().confirm==='import-rates'",
  'wait:200',
  'shot:fc-import',
  'tap:Escape',
  "until:window.__ui.screen==='title'",
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:Enter',
  "until:window.__ui.screen==='settings'",
  'wait:300',
  'shot:settings-fc',
  'tap:Escape',
  "until:window.__ui.screen==='title'",
  'tap:Enter',
  "until:window.__ui.screen==='flight'",
  'wait:400',
  'tap:Escape',
  "until:window.__ui.screen==='paused'",
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:ArrowDown',
  'tap:Enter',
  "until:window.__ui.screen==='fc'",
  "eval:void(window.__ui.fc.runActive=true,window.__ui.fc.setValue('p_roll','80'),window.__ui.renderMenu())",
  'expect:window.__fc().dirty',
  "eval:window.__ui.act('fc-save')",
  "until:window.__fc().confirm==='save-run'",
  'wait:200',
  'shot:fc-save-confirm',
  "eval:window.__ui.act('fc-save-restart')",
  "until:window.__ui.screen==='flight'",
  'wait:250',
  'eval:window.__fc()',
  'expect:(function(){var s=window.__fc();return s.simStepMs===s.moduleMs&&s.lastTs<=s.simStepMs/1000+1e-9;})()',
  'expect:(function(){return window.__fc().homage===true&&window.__fc().tabs===24;})()',
];

const child = spawn(
  process.execPath,
  ['scripts/shots.js', `--out=${here}`, '--w=1600', '--h=900', ...steps],
  {
    cwd: root,
    stdio: 'inherit',
    env: { ...process.env, SIM_CHROME_BIN: chrome },
  },
);
child.on('exit', (code) => process.exit(code ?? 1));
