/*
 * presets.js: the tracks that ship with the builder, and nothing else.
 *
 * GENERATED by scripts/racegow-lattice.js from the lattice specs in that
 * file. Edit the spec and run the script; do not edit this file by hand.
 *
 * Copyright (C) 2026 WebFPVSimulator contributors
 *
 * This file is part of WebFPVSimulator.
 *
 * WebFPVSimulator is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or (at
 * your option) any later version.
 *
 * WebFPVSimulator is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY, without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with WebFPVSimulator. If not, see <https://www.gnu.org/licenses/>.
 */

/*
 * THE RaceGOW5 SET, read off the official animations.
 *
 * RaceGOW is a home whoop time trial series: everybody builds the same track
 * out of the same 3/4 inch pipe kit in their own living room and flies it
 * against the same leaderboard. Each track is published as an animation of
 * one lap, gate by gate, and those animations are what these tracks are
 * built from, every frame of them.
 *
 * They can be built exactly because the kit is a lattice. Every pipe is 27
 * inches, every fitting is a right angle, so every gate is a 27 inch square
 * standing square to one of two axes or lying flat, and every distance is a
 * whole number of 27 inch units. Reading a track is counting which unit
 * squares the animation lights, in what order, flown which way. The count
 * for each track is in scripts/racegow-lattice.js, and this file is what
 * that script writes. A track that is not in that script is not here, which
 * is why the set is the size it is: the earlier six were reconstructions
 * from a single render, close in shape and wrong in detail, and the owner
 * replaced them.
 *
 * A pole is a marker whose pass panel is the animation's own: full height,
 * one side. It stands on the gate's stile line at RaceGOW's 14 inches from
 * the gate centre. The start gate is the first pass of the lap and the lap
 * closes on it.
 *
 * CREDIT GOES TO THE DESIGNER, one per track, as the site names them.
 */
export const PRESETS = [
  {
    "schemaVersion": 3,
    "id": "racegow5-track8",
    "name": "RaceGOW5 Track 8",
    "createdUtc": "2026-09-11T00:00:00Z",
    "modifiedUtc": "2026-09-11T00:00:00Z",
    "trackClass": "micro",
    "field": {
      "width": 10,
      "depth": 12,
      "gridSize": 0.0254
    },
    "settings": {
      "tangentScale": 1.1,
      "minCurveRadius": 0.45,
      "samplesPerSegment": 48
    },
    "branding": {
      "logos": []
    },
    "credit": {
      "designer": "AyyyKayyy",
      "series": "RaceGOW5",
      "sponsor": "weBLEEDfpv",
      "source": "racegow.com/tracks, the official Track 8 animation",
      "broughtOverBy": "andAgainFPV",
      "note": ""
    },
    "elements": [
      {
        "id": "el-1",
        "type": "startPads",
        "name": "",
        "position": {
          "x": 3.41376,
          "y": 5.6515,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "pads": 1,
          "spacing": 0.3,
          "padSize": 0.1
        }
      },
      {
        "id": "el-2",
        "type": "gate",
        "name": "Start gate",
        "position": {
          "x": 3.9624,
          "y": 5.6515,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-3",
        "type": "gate",
        "name": "Over the start gate",
        "position": {
          "x": 3.9624,
          "y": 5.6515,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-4",
        "type": "gate",
        "name": "Tower, bottom",
        "position": {
          "x": 6.0198,
          "y": 6.3373,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-5",
        "type": "gate",
        "name": "Tower, middle",
        "position": {
          "x": 6.0198,
          "y": 6.3373,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-6",
        "type": "gate",
        "name": "Tower, top",
        "position": {
          "x": 6.0198,
          "y": 6.3373,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 1.3716,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-7",
        "type": "gate",
        "name": "Far side, left, low",
        "position": {
          "x": 4.9911,
          "y": 6.6802,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-8",
        "type": "gate",
        "name": "Far side, left, up",
        "position": {
          "x": 4.9911,
          "y": 6.6802,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-9",
        "type": "gate",
        "name": "Far side, right, low",
        "position": {
          "x": 5.6769,
          "y": 6.6802,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-10",
        "type": "gate",
        "name": "Far side, right, up",
        "position": {
          "x": 5.6769,
          "y": 6.6802,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-11",
        "type": "gate",
        "name": "Under the rail",
        "position": {
          "x": 4.9911,
          "y": 5.9944,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-12",
        "type": "gate",
        "name": "Over the rail",
        "position": {
          "x": 4.9911,
          "y": 5.9944,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-13",
        "type": "diveGate",
        "name": "Table top",
        "position": {
          "x": 5.6769,
          "y": 6.3373,
          "z": 0
        },
        "yaw": 0,
        "pitch": 1.570796,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.356235,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-14",
        "type": "pole",
        "name": "Tall pole",
        "position": {
          "x": 6.0198,
          "y": 5.9817,
          "z": 0
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 2.0574,
          "poleRadius": 0.013335,
          "clearance": 0.3556
        }
      },
      {
        "id": "el-15",
        "type": "pole",
        "name": "Left pole",
        "position": {
          "x": 3.9624,
          "y": 6.0071,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 1.3716,
          "poleRadius": 0.013335,
          "clearance": 0.3556
        }
      },
      {
        "id": "el-16",
        "type": "waypoint",
        "name": "Over the tower",
        "position": {
          "x": 6.29412,
          "y": 6.3373,
          "z": 2.33172
        },
        "yaw": 3.141593,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-17",
        "type": "waypoint",
        "name": "Round the pole, low",
        "position": {
          "x": 6.43128,
          "y": 5.9944,
          "z": 0.48006
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-18",
        "type": "waypoint",
        "name": "Home straight",
        "position": {
          "x": 4.9911,
          "y": 5.6515,
          "z": 1.0287
        },
        "yaw": 3.141593,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-19",
        "type": "waypoint",
        "name": "Round the pole, mid",
        "position": {
          "x": 6.43128,
          "y": 6.3373,
          "z": 0.89154
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-20",
        "type": "waypoint",
        "name": "Behind the far side",
        "position": {
          "x": 5.6769,
          "y": 7.0231,
          "z": 1.16586
        },
        "yaw": 3.141593,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-21",
        "type": "waypoint",
        "name": "Outside the start gate",
        "position": {
          "x": 3.6195,
          "y": 5.10286,
          "z": 0.3429
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-22",
        "type": "horizontalPole",
        "name": "Rail",
        "position": {
          "x": 4.3053,
          "y": 5.9944,
          "z": 0.672465
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "width": 0.6858,
          "depth": 0.02667,
          "height": 0.02667
        }
      }
    ],
    "sequence": [
      {
        "id": "sq-1",
        "elementId": "el-2",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-2",
        "elementId": "el-14",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-3",
        "elementId": "el-6",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-4",
        "elementId": "el-14",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-5",
        "elementId": "el-5",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-6",
        "elementId": "el-3",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-7",
        "elementId": "el-15",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-8",
        "elementId": "el-10",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-9",
        "elementId": "el-8",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-10",
        "elementId": "el-12",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-11",
        "elementId": "el-11",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-12",
        "elementId": "el-7",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-13",
        "elementId": "el-9",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-14",
        "elementId": "el-14",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-15",
        "elementId": "el-19",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-16",
        "elementId": "el-20",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-17",
        "elementId": "el-8",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-18",
        "elementId": "el-5",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-19",
        "elementId": "el-14",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-20",
        "elementId": "el-6",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-21",
        "elementId": "el-16",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-22",
        "elementId": "el-4",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-23",
        "elementId": "el-17",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-24",
        "elementId": "el-18",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-25",
        "elementId": "el-15",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-26",
        "elementId": "el-3",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-27",
        "elementId": "el-12",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-28",
        "elementId": "el-11",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-29",
        "elementId": "el-14",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-30",
        "elementId": "el-5",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-31",
        "elementId": "el-6",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-32",
        "elementId": "el-14",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-33",
        "elementId": "el-13",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-34",
        "elementId": "el-11",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-35",
        "elementId": "el-21",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      }
    ]
  },
  {
    "schemaVersion": 3,
    "id": "racegow5-track5",
    "name": "RaceGOW5 Track 5",
    "createdUtc": "2026-09-11T00:00:00Z",
    "modifiedUtc": "2026-09-11T00:00:00Z",
    "trackClass": "micro",
    "field": {
      "width": 10,
      "depth": 12,
      "gridSize": 0.0254
    },
    "settings": {
      "tangentScale": 1.1,
      "minCurveRadius": 0.45,
      "samplesPerSegment": 48
    },
    "branding": {
      "logos": []
    },
    "credit": {
      "designer": "Cumber and Hotspur",
      "series": "RaceGOW5",
      "sponsor": "Neo's UV Creations",
      "source": "racegow.com/tracks, the official Track 5 animation",
      "broughtOverBy": "andAgainFPV",
      "note": ""
    },
    "elements": [
      {
        "id": "el-1",
        "type": "startPads",
        "name": "",
        "position": {
          "x": 5.334,
          "y": 5.6515,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "pads": 1,
          "spacing": 0.3,
          "padSize": 0.1
        }
      },
      {
        "id": "el-2",
        "type": "gate",
        "name": "Start gate",
        "position": {
          "x": 6.0198,
          "y": 5.6515,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-3",
        "type": "gate",
        "name": "Over the start gate",
        "position": {
          "x": 6.0198,
          "y": 5.6515,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-4",
        "type": "gate",
        "name": "Frame, bottom",
        "position": {
          "x": 5.334,
          "y": 6.3373,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-5",
        "type": "gate",
        "name": "Frame, middle",
        "position": {
          "x": 5.334,
          "y": 6.3373,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-6",
        "type": "gate",
        "name": "Frame, top",
        "position": {
          "x": 5.334,
          "y": 6.3373,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 1.3716,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-7",
        "type": "gate",
        "name": "Under the bar",
        "position": {
          "x": 5.6769,
          "y": 5.9944,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-8",
        "type": "gate",
        "name": "Under the rail",
        "position": {
          "x": 4.3053,
          "y": 5.9944,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-9",
        "type": "gate",
        "name": "Over the rail",
        "position": {
          "x": 4.3053,
          "y": 5.9944,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-10",
        "type": "gate",
        "name": "Near gate",
        "position": {
          "x": 3.9624,
          "y": 5.6515,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-11",
        "type": "gate",
        "name": "Over the near gate",
        "position": {
          "x": 3.9624,
          "y": 5.6515,
          "z": 0
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "levels": 1,
          "sillH": 0.6858,
          "clearW": 0.65913,
          "clearH": 0.65913,
          "levelPitch": 0.6858
        }
      },
      {
        "id": "el-12",
        "type": "pole",
        "name": "Right pole",
        "position": {
          "x": 6.0198,
          "y": 5.2959,
          "z": 0
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 1.3716,
          "poleRadius": 0.013335,
          "clearance": 0.3556
        }
      },
      {
        "id": "el-13",
        "type": "pole",
        "name": "Tall pole",
        "position": {
          "x": 5.334,
          "y": 6.6929,
          "z": 0
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 2.0574,
          "poleRadius": 0.013335,
          "clearance": 0.3556
        }
      },
      {
        "id": "el-14",
        "type": "pole",
        "name": "Near pole",
        "position": {
          "x": 3.9624,
          "y": 5.2959,
          "z": 0
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 1.3716,
          "poleRadius": 0.013335,
          "clearance": 0.3556
        }
      },
      {
        "id": "el-15",
        "type": "waypoint",
        "name": "Back past the frame",
        "position": {
          "x": 4.85394,
          "y": 7.366,
          "z": 0.54864
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-16",
        "type": "waypoint",
        "name": "Round the tall pole",
        "position": {
          "x": 5.81406,
          "y": 7.09168,
          "z": 0.82296
        },
        "yaw": 3.141593,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-17",
        "type": "waypoint",
        "name": "Round the tall pole again",
        "position": {
          "x": 5.05968,
          "y": 7.50316,
          "z": 0.61722
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-18",
        "type": "waypoint",
        "name": "Back over the rail",
        "position": {
          "x": 4.85394,
          "y": 6.20014,
          "z": 1.09728
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-19",
        "type": "waypoint",
        "name": "Round the right pole",
        "position": {
          "x": 6.43128,
          "y": 4.89712,
          "z": 1.64592
        },
        "yaw": -1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-20",
        "type": "waypoint",
        "name": "Round the near gate",
        "position": {
          "x": 3.6195,
          "y": 6.3373,
          "z": 0.82296
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-21",
        "type": "waypoint",
        "name": "Round the right pole, low",
        "position": {
          "x": 6.22554,
          "y": 4.55422,
          "z": 0.75438
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-22",
        "type": "waypoint",
        "name": "Round the left pole",
        "position": {
          "x": 3.55092,
          "y": 6.13156,
          "z": 1.09728
        },
        "yaw": 1.570796,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "height": 0.35,
          "poleRadius": 0.008,
          "clearance": 0
        }
      },
      {
        "id": "el-23",
        "type": "horizontalPole",
        "name": "Rail",
        "position": {
          "x": 4.9911,
          "y": 5.9944,
          "z": 0.672465
        },
        "yaw": 0,
        "pitch": 0,
        "yawOverridden": true,
        "dims": {
          "width": 0.6858,
          "depth": 0.02667,
          "height": 0.02667
        }
      }
    ],
    "sequence": [
      {
        "id": "sq-1",
        "elementId": "el-2",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-2",
        "elementId": "el-12",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-3",
        "elementId": "el-21",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-4",
        "elementId": "el-3",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-5",
        "elementId": "el-13",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-6",
        "elementId": "el-6",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-7",
        "elementId": "el-5",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-8",
        "elementId": "el-13",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-9",
        "elementId": "el-4",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-10",
        "elementId": "el-15",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-11",
        "elementId": "el-16",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-12",
        "elementId": "el-13",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-13",
        "elementId": "el-17",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-14",
        "elementId": "el-7",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-15",
        "elementId": "el-8",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-16",
        "elementId": "el-9",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-17",
        "elementId": "el-8",
        "apertureIndex": 0,
        "entry": 1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-18",
        "elementId": "el-18",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-19",
        "elementId": "el-11",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-20",
        "elementId": "el-22",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-21",
        "elementId": "el-13",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-22",
        "elementId": "el-19",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-23",
        "elementId": "el-12",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-24",
        "elementId": "el-11",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-25",
        "elementId": "el-14",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0.3556,
        "overridden": true
      },
      {
        "id": "sq-26",
        "elementId": "el-10",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      },
      {
        "id": "sq-27",
        "elementId": "el-20",
        "apertureIndex": null,
        "entry": null,
        "passSide": "left",
        "clearance": 0,
        "overridden": true
      },
      {
        "id": "sq-28",
        "elementId": "el-9",
        "apertureIndex": 0,
        "entry": -1,
        "passSide": null,
        "clearance": null,
        "overridden": true
      }
    ]
  },
];

/* Every preset that belongs to a track class, newest first is meaningless
 * here so they stay in the order the series numbers them. */
export function presetsForClass(cls) {
  return PRESETS.filter((d) => d.trackClass === cls);
}

/* The document for a preset id, or null. Returned as a deep copy, because
 * the caller edits what it is given and a shared module constant that the
 * builder mutates would change under every other reader. */
export function presetById(id) {
  const found = PRESETS.find((d) => d.id === id);
  return found ? JSON.parse(JSON.stringify(found)) : null;
}

/* Whether an id names a preset. storage.js uses it to keep a preset out of
 * the delete path and to know that a save is making a copy. */
export function isPresetId(id) {
  return PRESETS.some((d) => d.id === id);
}
